server:
  port: 8085
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: catalog-service
          uri: http://localhost:8081
          predicates:
            - Path=/catalog/**
        - id: invetory-service
          uri: http://localhost:8082
          predicates:
            Path=/inventory/**
        - id: product-service
          uri: http://localhost:8083
          predicates:
            Path=/product/**
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
