server:
  port: 8081

spring:
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/microservices_db
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true


