server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ruslanator/microservices_config.git
  application:
    name: config-server
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
